version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vnsm-backend
    restart: always
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://${DB_USER:-vnsm_user}:${DB_PASSWORD:-your_db_password}@host.docker.internal:3306/${DB_NAME:-vnsm_db}
      - DB_HOST=host.docker.internal
      - DB_USER=${DB_USER:-vnsm_user}
      - DB_PASSWORD=${DB_PASSWORD:-your_db_password}
      - DB_NAME=${DB_NAME:-vnsm_db}
      - DB_PORT=3306
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
    ports:
      - "3001:3001"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    networks:
      - vnsm-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vnsm-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.vsmi.vn
    networks:
      - vnsm-network

networks:
  vnsm-network:
    driver: bridge