version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: vnsm-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vmsi_db
      - MYSQL_USER=vmsi
      - MYSQL_PASSWORD=Timem.2302
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - vnsm-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vnsm-backend
    restart: always
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://${DB_USER:-vnsm_user}:${DB_PASSWORD:-your_db_password}@mysql:3306/${DB_NAME:-vnsm_db}
      - DB_HOST=mysql
      - DB_USER=${DB_USER:-vnsm_user}
      - DB_PASSWORD=${DB_PASSWORD:-your_db_password}
      - DB_NAME=${DB_NAME:-vnsm_db}
      - DB_PORT=3306
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
    ports:
      - "3001:3001"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    networks:
      - vnsm-network
    depends_on:
      - mysql

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vnsm-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.vsmi.vn/api
      - NODE_ENV=production
    networks:
      - vnsm-network

networks:
  vnsm-network:
    driver: bridge

volumes:
  mysql-data: