version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: vnsm-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Timem.2302
      - MYSQL_DATABASE=vsmi_db
      - MYSQL_USER=vsmi
      - MYSQL_PASSWORD=Timem.2302
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vnsm-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-pTimem.2302", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vnsm-backend
    restart: always
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://root:Timem.2302@mysql:3306/${DB_NAME:-vsmi_db}?connection_limit=5&pool_timeout=10&connect_timeout=20
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Timem.2302
      - DB_NAME=${DB_NAME:-vsmi_db}
      - DB_PORT=3306
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
    ports:
      - "3001:3001"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    networks:
      - vnsm-network
    depends_on:
      mysql:
        condition: service_healthy

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vnsm-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.vsmi.vn
      - NEXT_PUBLIC_API_BASE_URL=https://api.vsmi.vn
      - NODE_ENV=production
    networks:
      - vnsm-network

networks:
  vnsm-network:
    driver: bridge

volumes:
  mysql-data: