version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: vnsm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-your_db_password}
      MYSQL_DATABASE: ${DB_NAME:-vnsm_db}
      MYSQL_USER: ${DB_USER:-vnsm_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-your_db_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vnsm-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vnsm-backend
    restart: always
    depends_on:
      - db
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://${DB_USER:-vnsm_user}:${DB_PASSWORD:-your_db_password}@db:3306/${DB_NAME:-vnsm_db}
      - DB_HOST=db
      - DB_USER=${DB_USER:-vnsm_user}
      - DB_PASSWORD=${DB_PASSWORD:-your_db_password}
      - DB_NAME=${DB_NAME:-vnsm_db}
      - DB_PORT=3306
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1d}
    ports:
      - "3001:3001"
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    networks:
      - vnsm-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vnsm-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001/api
    networks:
      - vnsm-network

networks:
  vnsm-network:
    driver: bridge

volumes:
  mysql_data: